### ISSUE TITLE
error looking up function 'opus_decoder_create'

### ISSUE THREAD

**Issue by faminee** [DV8FromTheWorld/JDA-Player#25]
Heyy, I know that this is deprecated etc....
But is this a dependency issue?

`[00:35:02] [Fatal] [JDAAudioSocket]: java.lang.UnsatisfiedLinkError: Error looking up function 'opus_decoder_create': /usr/lib/jvm/java-8-openjdk/bin/java: undefined symbol: opus_decoder_create
	at com.sun.jna.Function.<init>(Function.java:212)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:541)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:518)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:504)
	at com.sun.jna.Library$Handler.invoke(Library.java:220)
	at com.sun.proxy.$Proxy0.opus_decoder_create(Unknown Source)
	at net.dv8tion.jda.audio.Decoder.<init>(Decoder.java:41)
	at net.dv8tion.jda.audio.AudioConnection.updateUserSSRC(AudioConnection.java:180)
	at net.dv8tion.jda.audio.AudioWebSocket.onTextMessage(AudioWebSocket.java:217)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)`

I'm running Linux
Distro - Arch

**Comment by din0s** [comment]
JDA-Player is deprecated and we will no longer offer support for possible issues and bugs.

Please use a more powerful lib like [**lavaplayer**](https://github.com/sedmelluq/lavaplayer), which is way more efficient and optimized, and runs exclusively on Java (no need for ffmpeg/ytdl/python).

If you have any questions feel free to join the [JDA Guild on Discord](https://discord.gg/0hMr4ce0tIk3pSjp) and request support in the lavaplayer channel.
